# Generated by Django 4.2.2 on 2023-06-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('kilometraje', models.FloatField()),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_vehiculo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehiculoDocumento',
            fields=[
                ('documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_vencimiento', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'tbl_vehiculo_documento',
                'managed': True,
            },
        ),
    ]
